Get linux-htc-dlx to compile
The following errors are fixed:

1. make[5]: *** No rule to make target 'drivers/i2c/chips/akm8963.o', needed by 'drivers/i2c/chips/built-in.o'.  Stop.

-> fixed by recreating the defconfig based on cyanogenmod_dlx_defconfig as specified here:
https://github.com/LineageOS/android_device_htc_dlx/blob/cm-10.2/BoardConfig.mk#L48
https://raw.githubusercontent.com/LineageOS/android_kernel_htc_m7/cm-14.0/arch/arm/configs/cyanogenmod_dlx_defconfig

2. /home/user/build/src/android_kernel_htc_m7-f6eb6496406f5a06cdd4716e494082d78df70e83/drivers/net/wireless/bcmdhd_4334_mcc/siutils.c:336:14:
error: self-comparison always evaluates to false [-Werror=tautological-compare]
  if (bustype != BUSTYPE(bustype)) {
cc1: all warnings being treated as errors

Fixed by removing -Werror as CFLAG in the bcmdhd driver.

3. Linker error with gpu-msm2 (just like in lg-mako): Fixed with the same patch as in lg-mako, but
adjusted for gpu-msm2 instead of gpu-msm.